import io
import os
import shutil
import stat
import subprocess
import sys
import urllib.request
import zipfile

# ======================= EDIT THESE IN COLAB =======================
# Which students to process (1-based, inclusive). Set END = None to go to the
# end of the list. These override START/END in config.json.
START = 1176
END = 1250
CONCURRENCY = 1      # how many browsers run in parallel
HEADLESS = True      # True on Colab (no display); False to watch the browser
# ===================================================================

# The repo is now a full Node.js project at its root (runner + node_modules
# committed), so we git clone it directly. The archive zip is kept only as a
# no-git fallback; GitHub serves it under /archive/refs/heads/<branch>.zip.
REPO_URL = "https://github.com/AbdulkhaevHasanboy/Script.git"
ZIP_URLS = [
    "https://github.com/AbdulkhaevHasanboy/Script/archive/refs/heads/main.zip",
    "https://github.com/AbdulkhaevHasanboy/Script/archive/refs/heads/master.zip",
]
EXTRACT_DIR = "SCRIPT"

# The runner JS is the anchor: the project root is whatever dir contains it.
RUNNER_JS = "coursera_manual_runner.js"

# Data files that are NOT committed to the public repo (they hold student
# emails/passwords). Upload these to the Colab session first (drag them into the
# file panel, or use files.upload()); the bootstrap copies whatever it finds in
# the current dir into the extracted project. students.csv is required.
DATA_FILES = [
    "students.csv",
    "names.xlsx",
    "recorded_steps.json",
    "recorded_steps.backup.json",
    "config.json",
]


def have_git():
    try:
        subprocess.check_output("git --version", shell=True, text=True)
        return True
    except Exception:  # noqa: BLE001
        return False


def fetch_repo():
    """Get the project into ./EXTRACT_DIR and return that path.

    Preferred: a shallow git clone of the whole Node.js project. Fallback (no
    git available): download and unpack the GitHub archive zip.
    """
    # Start clean so re-running the cell doesn't fail on an existing dir.
    shutil.rmtree(EXTRACT_DIR, ignore_errors=True)

    if have_git():
        print(f"Cloning {REPO_URL} -> ./{EXTRACT_DIR} ...")
        proc = subprocess.run(
            f'git clone --depth 1 "{REPO_URL}" "{EXTRACT_DIR}"',
            shell=True,
        )
        if proc.returncode == 0:
            return EXTRACT_DIR
        print("  git clone failed; falling back to the archive zip.")

    # --- zip fallback ---
    last_err = None
    for url in ZIP_URLS:
        try:
            print(f"Downloading {url} ...")
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
            with urllib.request.urlopen(req) as resp:
                data = resp.read()
            print(f"Downloaded {len(data)} bytes; extracting into ./{EXTRACT_DIR} ...")
            os.makedirs(EXTRACT_DIR, exist_ok=True)
            with zipfile.ZipFile(io.BytesIO(data)) as zf:
                zf.extractall(EXTRACT_DIR)
            return EXTRACT_DIR
        except Exception as e:  # noqa: BLE001
            print(f"  failed: {e}")
            last_err = e
    raise SystemExit(f"Could not fetch the project. Last error: {last_err}")


# A known-good run_on_colab.py. We always write this into the extracted project,
# overwriting whatever stale copy shipped in the zip, so setup is reliable
# regardless of what is committed in the repo.
ROBUST_RUNNER = r'''#!/usr/bin/env python3
"""Auto-generated by bootstrap.py: set up and run the Coursera runner."""

import os
import stat
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
os.chdir(HERE)


def run(cmd, env=None):
    print(f"\n$ {cmd}", flush=True)
    proc = subprocess.Popen(
        cmd, shell=True, env=env,
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1,
    )
    for line in proc.stdout:
        print(line, end="", flush=True)
    proc.wait()
    if proc.returncode != 0:
        print(f"[command failed: exit {proc.returncode}]", flush=True)
    return proc.returncode == 0


def node_major_version():
    try:
        out = subprocess.check_output("node -v", shell=True, text=True).strip()
        return int(out.lstrip("v").split(".")[0])
    except Exception:
        return 0


print("=== Setting up environment for the Coursera runner ===")

if node_major_version() >= 18:
    print(f"Found Node.js {subprocess.check_output('node -v', shell=True, text=True).strip()}")
else:
    print("Installing Node.js 20 LTS (Playwright requires v18+)...")
    run("apt-get update -y && apt-get install -y curl")
    run("curl -fsSL https://deb.nodesource.com/setup_20.x | bash -")
    run("apt-get install -y nodejs")
    if node_major_version() < 18:
        sys.exit("Error: Node.js 18+ is required but could not be installed.")

run("node -v")
run("npm -v")

# names.xlsx is parsed by the Node runner via `python3 -c "import openpyxl ..."`,
# so the python3 the runner shells out to must have openpyxl. Colab usually ships
# it, but install it defensively so the run never dies with "No module named
# 'openpyxl'". openpyxl is a Python package; it must NOT be in the npm list.
try:
    import openpyxl  # noqa: F401
    print("openpyxl already available.")
except ImportError:
    print("Installing openpyxl (needed to read names.xlsx)...")
    if not (run(f'"{sys.executable}" -m pip install -q openpyxl')
            or run("python3 -m pip install -q openpyxl")
            or run("pip3 install -q openpyxl")):
        sys.exit("Error installing openpyxl (required to read names.xlsx).")

if not run("npm install playwright playwright-extra puppeteer-extra-plugin-stealth"):
    sys.exit("Error installing npm dependencies.")

# Repair +x bits stripped by zip extraction so npx/.bin shims can execute.
bin_dir = os.path.join(HERE, "node_modules", ".bin")
if os.path.isdir(bin_dir):
    for name in os.listdir(bin_dir):
        path = os.path.join(bin_dir, name)
        try:
            mode = os.stat(path).st_mode
            os.chmod(path, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        except OSError:
            pass

browsers = "chromium firefox webkit"
cli = os.path.join(HERE, "node_modules", "playwright", "cli.js")
if os.path.exists(cli):
    with_deps = f'node "{cli}" install {browsers} --with-deps'
    plain = f'node "{cli}" install {browsers}'
else:
    with_deps = f"npx playwright install {browsers} --with-deps"
    plain = f"npx playwright install {browsers}"
if not (run(with_deps) or run(plain)):
    sys.exit("Error installing Playwright browsers.")

if not os.path.exists("students.csv"):
    sys.exit("Error: students.csv not found next to the runner. Upload it to the "
             "Colab session before running bootstrap.py.")

print("\n=== Setup complete! Starting the runner (MODE=auto) ===")
if not run("node coursera_manual_runner.js", env=dict(os.environ, MODE="auto")):
    sys.exit("The runner exited with an error.")
'''


def find_project_dir(base):
    # The project root is the directory containing the runner JS. Skip node_modules.
    for root, dirs, files in os.walk(base):
        dirs[:] = [d for d in dirs if d != "node_modules"]
        if RUNNER_JS in files:
            return root
    return None


def provision_data_files(project_dir):
    """Copy the not-committed data files (students.csv, etc.) from the Colab
    working dir into the project, since they are no longer in the GitHub zip."""
    cwd = os.getcwd()
    copied = []
    for name in DATA_FILES:
        dest = os.path.join(project_dir, name)
        if os.path.exists(dest):
            continue  # already shipped in the zip (e.g. recorded_steps.json)
        src = os.path.join(cwd, name)
        if os.path.exists(src) and os.path.abspath(src) != os.path.abspath(dest):
            shutil.copy2(src, dest)
            copied.append(name)
    if copied:
        print(f"Provisioned uploaded data files into the project: {', '.join(copied)}")

    if not os.path.exists(os.path.join(project_dir, "students.csv")):
        raise SystemExit(
            "students.csv was not found. It is no longer in the public repo, so "
            "you must upload it to the Colab session (drag it into the file panel, "
            "or use files.upload()) BEFORE running bootstrap.py."
        )


def run_project(base):
    project_dir = find_project_dir(base)
    if not project_dir:
        listing = "\n".join(
            os.path.join(r, f) for r, _d, fs in os.walk(base) for f in fs
        )
        raise SystemExit(
            f"Could not find {RUNNER_JS} in the project.\n"
            f"Extracted files:\n{listing}"
        )

    # Always install a known-good setup script, overwriting any stale copy.
    runner_path = os.path.join(project_dir, "run_on_colab.py")
    with open(runner_path, "w", encoding="utf-8") as fh:
        fh.write(ROBUST_RUNNER)
    print(f"Installed fresh run_on_colab.py into {project_dir}")

    # Bring in the data files the repo no longer ships (students.csv, etc.).
    provision_data_files(project_dir)

    # Pass the Colab-side knobs through as env vars; the runner reads START/END/
    # CONCURRENCY/HEADLESS from the environment first, then config.json.
    env = dict(os.environ)
    env["START"] = str(START)
    if END is not None:
        env["END"] = str(END)
    else:
        env.pop("END", None)
    env["CONCURRENCY"] = str(CONCURRENCY)
    env["HEADLESS"] = "y" if HEADLESS else "n"

    cmd = [sys.executable, "run_on_colab.py"]
    print(f"\n=== Running {' '.join(cmd)} in {project_dir} "
          f"(START={START}, END={END}, CONCURRENCY={CONCURRENCY}, "
          f"HEADLESS={HEADLESS}) ===", flush=True)

    # Stream the child's output straight through — no screenshot viewer.
    proc = subprocess.Popen(
        cmd,
        cwd=project_dir,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    for line in proc.stdout:
        print(line, end="", flush=True)
    proc.wait()

    if proc.returncode != 0:
        raise SystemExit(
            f"\nProject exited with code {proc.returncode}. See the output above "
            "for the error (e.g. missing students.csv, npm/playwright failure)."
        )


def main():
    project_base = fetch_repo()
    run_project(project_base)


if __name__ == "__main__":
    main()
